/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BanTestStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-24T15:11:21.199Z[GMT]")
public class BanTestStatus {
  public static final String SERIALIZED_NAME_BANNED = "banned";
  @SerializedName(SERIALIZED_NAME_BANNED)
  private Boolean banned;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_BAN_PHONE_MASK = "banPhoneMask";
  @SerializedName(SERIALIZED_NAME_BAN_PHONE_MASK)
  private String banPhoneMask;


  public BanTestStatus banned(Boolean banned) {
    
    this.banned = banned;
    return this;
  }

   /**
   * Get banned
   * @return banned
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getBanned() {
    return banned;
  }



  public void setBanned(Boolean banned) {
    this.banned = banned;
  }


  public BanTestStatus message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Do not write to me, otherwise I will send you a ban", value = "")

  public String getMessage() {
    return message;
  }



  public void setMessage(String message) {
    this.message = message;
  }


  public BanTestStatus phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Test phone number
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "17472822486", value = "Test phone number")

  public String getPhone() {
    return phone;
  }



  public void setPhone(String phone) {
    this.phone = phone;
  }


  public BanTestStatus banPhoneMask(String banPhoneMask) {
    
    this.banPhoneMask = banPhoneMask;
    return this;
  }

   /**
   * Test regex
   * @return banPhoneMask
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Test regex")

  public String getBanPhoneMask() {
    return banPhoneMask;
  }



  public void setBanPhoneMask(String banPhoneMask) {
    this.banPhoneMask = banPhoneMask;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BanTestStatus banTestStatus = (BanTestStatus) o;
    return Objects.equals(this.banned, banTestStatus.banned) &&
        Objects.equals(this.message, banTestStatus.message) &&
        Objects.equals(this.phone, banTestStatus.phone) &&
        Objects.equals(this.banPhoneMask, banTestStatus.banPhoneMask);
  }

  @Override
  public int hashCode() {
    return Objects.hash(banned, message, phone, banPhoneMask);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BanTestStatus {\n");
    sb.append("    banned: ").append(toIndentedString(banned)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    banPhoneMask: ").append(toIndentedString(banPhoneMask)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

