/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Chat;

/**
 * Chats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-24T15:11:21.199Z[GMT]")
public class Chats {
  public static final String SERIALIZED_NAME_DIALOGS = "dialogs";
  @SerializedName(SERIALIZED_NAME_DIALOGS)
  private List<Chat> dialogs = null;


  public Chats dialogs(List<Chat> dialogs) {
    
    this.dialogs = dialogs;
    return this;
  }

  public Chats addDialogsItem(Chat dialogsItem) {
    if (this.dialogs == null) {
      this.dialogs = new ArrayList<Chat>();
    }
    this.dialogs.add(dialogsItem);
    return this;
  }

   /**
   * Get dialogs
   * @return dialogs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Chat> getDialogs() {
    return dialogs;
  }



  public void setDialogs(List<Chat> dialogs) {
    this.dialogs = dialogs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Chats chats = (Chats) o;
    return Objects.equals(this.dialogs, chats.dialogs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dialogs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Chats {\n");
    sb.append("    dialogs: ").append(toIndentedString(dialogs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

