/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * An object that lists the fields changed in the request
 */
@ApiModel(description = "An object that lists the fields changed in the request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-24T15:11:21.199Z[GMT]")
public class InlineResponse2005Update {
  public static final String SERIALIZED_NAME_WEBHOOK_URL = "webhookUrl";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_URL)
  private String webhookUrl;

  public static final String SERIALIZED_NAME_ACK_NOTIFICATIONS_ON = "ackNotificationsOn";
  @SerializedName(SERIALIZED_NAME_ACK_NOTIFICATIONS_ON)
  private Boolean ackNotificationsOn;

  public static final String SERIALIZED_NAME_CHAT_UPDATE_ON = "chatUpdateOn";
  @SerializedName(SERIALIZED_NAME_CHAT_UPDATE_ON)
  private Boolean chatUpdateOn;

  public static final String SERIALIZED_NAME_VIDEO_UPLOAD_ON = "videoUploadOn";
  @SerializedName(SERIALIZED_NAME_VIDEO_UPLOAD_ON)
  private Boolean videoUploadOn;

  public static final String SERIALIZED_NAME_PROXY = "proxy";
  @SerializedName(SERIALIZED_NAME_PROXY)
  private String proxy;

  public static final String SERIALIZED_NAME_GUARANTEED_HOOKS = "guaranteedHooks";
  @SerializedName(SERIALIZED_NAME_GUARANTEED_HOOKS)
  private Boolean guaranteedHooks;

  public static final String SERIALIZED_NAME_IGNORE_OLD_MESSAGES = "ignoreOldMessages";
  @SerializedName(SERIALIZED_NAME_IGNORE_OLD_MESSAGES)
  private Boolean ignoreOldMessages;

  public static final String SERIALIZED_NAME_PROCESS_ARCHIVE = "processArchive";
  @SerializedName(SERIALIZED_NAME_PROCESS_ARCHIVE)
  private Boolean processArchive;

  public static final String SERIALIZED_NAME_INSTANCE_STATUSES = "instanceStatuses";
  @SerializedName(SERIALIZED_NAME_INSTANCE_STATUSES)
  private Boolean instanceStatuses;

  public static final String SERIALIZED_NAME_WEBHOOK_STATUSES = "webhookStatuses";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_STATUSES)
  private Boolean webhookStatuses;

  public static final String SERIALIZED_NAME_STATUS_NOTIFICATIONS_ON = "statusNotificationsOn";
  @SerializedName(SERIALIZED_NAME_STATUS_NOTIFICATIONS_ON)
  private Boolean statusNotificationsOn;


  public InlineResponse2005Update webhookUrl(String webhookUrl) {
    
    this.webhookUrl = webhookUrl;
    return this;
  }

   /**
   * Get webhookUrl
   * @return webhookUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://bin.chat-api.com/1f9aj261", value = "")

  public String getWebhookUrl() {
    return webhookUrl;
  }



  public void setWebhookUrl(String webhookUrl) {
    this.webhookUrl = webhookUrl;
  }


  public InlineResponse2005Update ackNotificationsOn(Boolean ackNotificationsOn) {
    
    this.ackNotificationsOn = ackNotificationsOn;
    return this;
  }

   /**
   * Get ackNotificationsOn
   * @return ackNotificationsOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getAckNotificationsOn() {
    return ackNotificationsOn;
  }



  public void setAckNotificationsOn(Boolean ackNotificationsOn) {
    this.ackNotificationsOn = ackNotificationsOn;
  }


  public InlineResponse2005Update chatUpdateOn(Boolean chatUpdateOn) {
    
    this.chatUpdateOn = chatUpdateOn;
    return this;
  }

   /**
   * Get chatUpdateOn
   * @return chatUpdateOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getChatUpdateOn() {
    return chatUpdateOn;
  }



  public void setChatUpdateOn(Boolean chatUpdateOn) {
    this.chatUpdateOn = chatUpdateOn;
  }


  public InlineResponse2005Update videoUploadOn(Boolean videoUploadOn) {
    
    this.videoUploadOn = videoUploadOn;
    return this;
  }

   /**
   * Get videoUploadOn
   * @return videoUploadOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getVideoUploadOn() {
    return videoUploadOn;
  }



  public void setVideoUploadOn(Boolean videoUploadOn) {
    this.videoUploadOn = videoUploadOn;
  }


  public InlineResponse2005Update proxy(String proxy) {
    
    this.proxy = proxy;
    return this;
  }

   /**
   * Get proxy
   * @return proxy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "8.8.8.8:4888", value = "")

  public String getProxy() {
    return proxy;
  }



  public void setProxy(String proxy) {
    this.proxy = proxy;
  }


  public InlineResponse2005Update guaranteedHooks(Boolean guaranteedHooks) {
    
    this.guaranteedHooks = guaranteedHooks;
    return this;
  }

   /**
   * Get guaranteedHooks
   * @return guaranteedHooks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getGuaranteedHooks() {
    return guaranteedHooks;
  }



  public void setGuaranteedHooks(Boolean guaranteedHooks) {
    this.guaranteedHooks = guaranteedHooks;
  }


  public InlineResponse2005Update ignoreOldMessages(Boolean ignoreOldMessages) {
    
    this.ignoreOldMessages = ignoreOldMessages;
    return this;
  }

   /**
   * Get ignoreOldMessages
   * @return ignoreOldMessages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIgnoreOldMessages() {
    return ignoreOldMessages;
  }



  public void setIgnoreOldMessages(Boolean ignoreOldMessages) {
    this.ignoreOldMessages = ignoreOldMessages;
  }


  public InlineResponse2005Update processArchive(Boolean processArchive) {
    
    this.processArchive = processArchive;
    return this;
  }

   /**
   * Get processArchive
   * @return processArchive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getProcessArchive() {
    return processArchive;
  }



  public void setProcessArchive(Boolean processArchive) {
    this.processArchive = processArchive;
  }


  public InlineResponse2005Update instanceStatuses(Boolean instanceStatuses) {
    
    this.instanceStatuses = instanceStatuses;
    return this;
  }

   /**
   * Get instanceStatuses
   * @return instanceStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getInstanceStatuses() {
    return instanceStatuses;
  }



  public void setInstanceStatuses(Boolean instanceStatuses) {
    this.instanceStatuses = instanceStatuses;
  }


  public InlineResponse2005Update webhookStatuses(Boolean webhookStatuses) {
    
    this.webhookStatuses = webhookStatuses;
    return this;
  }

   /**
   * Get webhookStatuses
   * @return webhookStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getWebhookStatuses() {
    return webhookStatuses;
  }



  public void setWebhookStatuses(Boolean webhookStatuses) {
    this.webhookStatuses = webhookStatuses;
  }


  public InlineResponse2005Update statusNotificationsOn(Boolean statusNotificationsOn) {
    
    this.statusNotificationsOn = statusNotificationsOn;
    return this;
  }

   /**
   * Get statusNotificationsOn
   * @return statusNotificationsOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getStatusNotificationsOn() {
    return statusNotificationsOn;
  }



  public void setStatusNotificationsOn(Boolean statusNotificationsOn) {
    this.statusNotificationsOn = statusNotificationsOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005Update inlineResponse2005Update = (InlineResponse2005Update) o;
    return Objects.equals(this.webhookUrl, inlineResponse2005Update.webhookUrl) &&
        Objects.equals(this.ackNotificationsOn, inlineResponse2005Update.ackNotificationsOn) &&
        Objects.equals(this.chatUpdateOn, inlineResponse2005Update.chatUpdateOn) &&
        Objects.equals(this.videoUploadOn, inlineResponse2005Update.videoUploadOn) &&
        Objects.equals(this.proxy, inlineResponse2005Update.proxy) &&
        Objects.equals(this.guaranteedHooks, inlineResponse2005Update.guaranteedHooks) &&
        Objects.equals(this.ignoreOldMessages, inlineResponse2005Update.ignoreOldMessages) &&
        Objects.equals(this.processArchive, inlineResponse2005Update.processArchive) &&
        Objects.equals(this.instanceStatuses, inlineResponse2005Update.instanceStatuses) &&
        Objects.equals(this.webhookStatuses, inlineResponse2005Update.webhookStatuses) &&
        Objects.equals(this.statusNotificationsOn, inlineResponse2005Update.statusNotificationsOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhookUrl, ackNotificationsOn, chatUpdateOn, videoUploadOn, proxy, guaranteedHooks, ignoreOldMessages, processArchive, instanceStatuses, webhookStatuses, statusNotificationsOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005Update {\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("    ackNotificationsOn: ").append(toIndentedString(ackNotificationsOn)).append("\n");
    sb.append("    chatUpdateOn: ").append(toIndentedString(chatUpdateOn)).append("\n");
    sb.append("    videoUploadOn: ").append(toIndentedString(videoUploadOn)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("    guaranteedHooks: ").append(toIndentedString(guaranteedHooks)).append("\n");
    sb.append("    ignoreOldMessages: ").append(toIndentedString(ignoreOldMessages)).append("\n");
    sb.append("    processArchive: ").append(toIndentedString(processArchive)).append("\n");
    sb.append("    instanceStatuses: ").append(toIndentedString(instanceStatuses)).append("\n");
    sb.append("    webhookStatuses: ").append(toIndentedString(webhookStatuses)).append("\n");
    sb.append("    statusNotificationsOn: ").append(toIndentedString(statusNotificationsOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

