/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.InstanceStatusAction;
import org.openapitools.client.model.InstanceStatusLink;

/**
 * Actions that can be applied to change the status
 */
@ApiModel(description = "Actions that can be applied to change the status")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-24T15:11:21.199Z[GMT]")
public class InstanceStatusStatusDataActions {
  public static final String SERIALIZED_NAME_EXPIRY = "expiry";
  @SerializedName(SERIALIZED_NAME_EXPIRY)
  private InstanceStatusAction expiry;

  public static final String SERIALIZED_NAME_RETRY = "retry";
  @SerializedName(SERIALIZED_NAME_RETRY)
  private InstanceStatusAction retry;

  public static final String SERIALIZED_NAME_LOGOUT = "logout";
  @SerializedName(SERIALIZED_NAME_LOGOUT)
  private InstanceStatusAction logout;

  public static final String SERIALIZED_NAME_TAKEOVER = "takeover";
  @SerializedName(SERIALIZED_NAME_TAKEOVER)
  private InstanceStatusAction takeover;

  public static final String SERIALIZED_NAME_LEARN_MORE = "learn_more";
  @SerializedName(SERIALIZED_NAME_LEARN_MORE)
  private InstanceStatusLink learnMore;


  public InstanceStatusStatusDataActions expiry(InstanceStatusAction expiry) {
    
    this.expiry = expiry;
    return this;
  }

   /**
   * Get expiry
   * @return expiry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstanceStatusAction getExpiry() {
    return expiry;
  }



  public void setExpiry(InstanceStatusAction expiry) {
    this.expiry = expiry;
  }


  public InstanceStatusStatusDataActions retry(InstanceStatusAction retry) {
    
    this.retry = retry;
    return this;
  }

   /**
   * Get retry
   * @return retry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstanceStatusAction getRetry() {
    return retry;
  }



  public void setRetry(InstanceStatusAction retry) {
    this.retry = retry;
  }


  public InstanceStatusStatusDataActions logout(InstanceStatusAction logout) {
    
    this.logout = logout;
    return this;
  }

   /**
   * Get logout
   * @return logout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstanceStatusAction getLogout() {
    return logout;
  }



  public void setLogout(InstanceStatusAction logout) {
    this.logout = logout;
  }


  public InstanceStatusStatusDataActions takeover(InstanceStatusAction takeover) {
    
    this.takeover = takeover;
    return this;
  }

   /**
   * Get takeover
   * @return takeover
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstanceStatusAction getTakeover() {
    return takeover;
  }



  public void setTakeover(InstanceStatusAction takeover) {
    this.takeover = takeover;
  }


  public InstanceStatusStatusDataActions learnMore(InstanceStatusLink learnMore) {
    
    this.learnMore = learnMore;
    return this;
  }

   /**
   * Get learnMore
   * @return learnMore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstanceStatusLink getLearnMore() {
    return learnMore;
  }



  public void setLearnMore(InstanceStatusLink learnMore) {
    this.learnMore = learnMore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstanceStatusStatusDataActions instanceStatusStatusDataActions = (InstanceStatusStatusDataActions) o;
    return Objects.equals(this.expiry, instanceStatusStatusDataActions.expiry) &&
        Objects.equals(this.retry, instanceStatusStatusDataActions.retry) &&
        Objects.equals(this.logout, instanceStatusStatusDataActions.logout) &&
        Objects.equals(this.takeover, instanceStatusStatusDataActions.takeover) &&
        Objects.equals(this.learnMore, instanceStatusStatusDataActions.learnMore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiry, retry, logout, takeover, learnMore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstanceStatusStatusDataActions {\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    retry: ").append(toIndentedString(retry)).append("\n");
    sb.append("    logout: ").append(toIndentedString(logout)).append("\n");
    sb.append("    takeover: ").append(toIndentedString(takeover)).append("\n");
    sb.append("    learnMore: ").append(toIndentedString(learnMore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

