/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Message;

/**
 * Messages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-24T15:11:21.199Z[GMT]")
public class Messages {
  public static final String SERIALIZED_NAME_MESSAGES = "messages";
  @SerializedName(SERIALIZED_NAME_MESSAGES)
  private List<Message> messages = null;

  public static final String SERIALIZED_NAME_LAST_MESSAGE_NUMBER = "lastMessageNumber";
  @SerializedName(SERIALIZED_NAME_LAST_MESSAGE_NUMBER)
  private Integer lastMessageNumber;


  public Messages messages(List<Message> messages) {
    
    this.messages = messages;
    return this;
  }

  public Messages addMessagesItem(Message messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<Message>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Message> getMessages() {
    return messages;
  }



  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }


  public Messages lastMessageNumber(Integer lastMessageNumber) {
    
    this.lastMessageNumber = lastMessageNumber;
    return this;
  }

   /**
   * next query should be /messages?lastMessageNumber&#x3D;199
   * @return lastMessageNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "199", value = "next query should be /messages?lastMessageNumber=199")

  public Integer getLastMessageNumber() {
    return lastMessageNumber;
  }



  public void setLastMessageNumber(Integer lastMessageNumber) {
    this.lastMessageNumber = lastMessageNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Messages messages = (Messages) o;
    return Objects.equals(this.messages, messages.messages) &&
        Objects.equals(this.lastMessageNumber, messages.lastMessageNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, lastMessageNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Messages {\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    lastMessageNumber: ").append(toIndentedString(lastMessageNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

