/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.OutboundMessage;

/**
 * OutboundMessages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-24T15:11:21.199Z[GMT]")
public class OutboundMessages {
  public static final String SERIALIZED_NAME_TOTAL_MESSAGES = "totalMessages";
  @SerializedName(SERIALIZED_NAME_TOTAL_MESSAGES)
  private Integer totalMessages;

  public static final String SERIALIZED_NAME_FIRST100 = "first100";
  @SerializedName(SERIALIZED_NAME_FIRST100)
  private List<OutboundMessage> first100 = null;


  public OutboundMessages totalMessages(Integer totalMessages) {
    
    this.totalMessages = totalMessages;
    return this;
  }

   /**
   * Total number of messages in the queue
   * @return totalMessages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "199", value = "Total number of messages in the queue")

  public Integer getTotalMessages() {
    return totalMessages;
  }



  public void setTotalMessages(Integer totalMessages) {
    this.totalMessages = totalMessages;
  }


  public OutboundMessages first100(List<OutboundMessage> first100) {
    
    this.first100 = first100;
    return this;
  }

  public OutboundMessages addFirst100Item(OutboundMessage first100Item) {
    if (this.first100 == null) {
      this.first100 = new ArrayList<OutboundMessage>();
    }
    this.first100.add(first100Item);
    return this;
  }

   /**
   * Get first100
   * @return first100
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OutboundMessage> getFirst100() {
    return first100;
  }



  public void setFirst100(List<OutboundMessage> first100) {
    this.first100 = first100;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutboundMessages outboundMessages = (OutboundMessages) o;
    return Objects.equals(this.totalMessages, outboundMessages.totalMessages) &&
        Objects.equals(this.first100, outboundMessages.first100);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalMessages, first100);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutboundMessages {\n");
    sb.append("    totalMessages: ").append(toIndentedString(totalMessages)).append("\n");
    sb.append("    first100: ").append(toIndentedString(first100)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

