/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WebhookStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-24T15:11:21.199Z[GMT]")
public class WebhookStatus {
  public static final String SERIALIZED_NAME_MSG_ID = "msgId";
  @SerializedName(SERIALIZED_NAME_MSG_ID)
  private String msgId;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private String time;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;


  public WebhookStatus msgId(String msgId) {
    
    this.msgId = msgId;
    return this;
  }

   /**
   * message id
   * @return msgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false_17472822486@c.us_DF38E6A25B42CC8CCE57EC40F", value = "message id")

  public String getMsgId() {
    return msgId;
  }



  public void setMsgId(String msgId) {
    this.msgId = msgId;
  }


  public WebhookStatus time(String time) {
    
    this.time = time;
    return this;
  }

   /**
   * creation date
   * @return time
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-10-07T21:40:55.000Z", value = "creation date")

  public String getTime() {
    return time;
  }



  public void setTime(String time) {
    this.time = time;
  }


  public WebhookStatus status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * status name (\&quot;sent\&quot;, \&quot;not sent\&quot;, \&quot;queued\&quot;)
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "sent", value = "status name (\"sent\", \"not sent\", \"queued\")")

  public String getStatus() {
    return status;
  }



  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookStatus webhookStatus = (WebhookStatus) o;
    return Objects.equals(this.msgId, webhookStatus.msgId) &&
        Objects.equals(this.time, webhookStatus.time) &&
        Objects.equals(this.status, webhookStatus.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msgId, time, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookStatus {\n");
    sb.append("    msgId: ").append(toIndentedString(msgId)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

