/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BanSettings
 */
public class BanSettingsTest {
    private final BanSettings model = new BanSettings();

    /**
     * Model tests for BanSettings
     */
    @Test
    public void testBanSettings() {
        // TODO: test BanSettings
    }

    /**
     * Test the property 'banPhoneMask'
     */
    @Test
    public void banPhoneMaskTest() {
        // TODO: test banPhoneMask
    }

    /**
     * Test the property 'preBanMessage'
     */
    @Test
    public void preBanMessageTest() {
        // TODO: test preBanMessage
    }

    /**
     * Test the property 'set'
     */
    @Test
    public void setTest() {
        // TODO: test set
    }

}
