/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.InlineResponse2005Update;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2005
 */
public class InlineResponse2005Test {
    private final InlineResponse2005 model = new InlineResponse2005();

    /**
     * Model tests for InlineResponse2005
     */
    @Test
    public void testInlineResponse2005() {
        // TODO: test InlineResponse2005
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

    /**
     * Test the property 'ackNotificationsOn'
     */
    @Test
    public void ackNotificationsOnTest() {
        // TODO: test ackNotificationsOn
    }

    /**
     * Test the property 'chatUpdateOn'
     */
    @Test
    public void chatUpdateOnTest() {
        // TODO: test chatUpdateOn
    }

    /**
     * Test the property 'videoUploadOn'
     */
    @Test
    public void videoUploadOnTest() {
        // TODO: test videoUploadOn
    }

    /**
     * Test the property 'proxy'
     */
    @Test
    public void proxyTest() {
        // TODO: test proxy
    }

    /**
     * Test the property 'guaranteedHooks'
     */
    @Test
    public void guaranteedHooksTest() {
        // TODO: test guaranteedHooks
    }

    /**
     * Test the property 'ignoreOldMessages'
     */
    @Test
    public void ignoreOldMessagesTest() {
        // TODO: test ignoreOldMessages
    }

    /**
     * Test the property 'processArchive'
     */
    @Test
    public void processArchiveTest() {
        // TODO: test processArchive
    }

    /**
     * Test the property 'instanceStatuses'
     */
    @Test
    public void instanceStatusesTest() {
        // TODO: test instanceStatuses
    }

    /**
     * Test the property 'webhookStatuses'
     */
    @Test
    public void webhookStatusesTest() {
        // TODO: test webhookStatuses
    }

    /**
     * Test the property 'statusNotificationsOn'
     */
    @Test
    public void statusNotificationsOnTest() {
        // TODO: test statusNotificationsOn
    }

    /**
     * Test the property 'update'
     */
    @Test
    public void updateTest() {
        // TODO: test update
    }

}
