package blood4life.User.presentacion.PresentacionCliente;

import blood4life.User.domain.services.ServiceModel;
import blood4life.commons.domain.Cita;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * Es un observador
 *
 * @author ahurtado
 */
public class GuiCitasDisponibles extends javax.swing.JFrame {

    ServiceModel service;
    JTable table;
    DefaultTableModel model;
    Date before;
    Date after;
    int lugarCita;
    List<Cita> listaCita;

    /**
     * Creates new form GUIListadoProductos
     *
     * @param service servicio
     */
    public GuiCitasDisponibles() {
    }
    
    public GuiCitasDisponibles(ServiceModel service) {
        parametrosInicializacion(service);
    }
    
    public GuiCitasDisponibles(ServiceModel service, Date before, Date after, int lugarCita) throws Exception {
        parametrosInicializacion(service);
        this.before = before;
        this.after = after;
        this.lugarCita = lugarCita;
        this.listaCita = new ArrayList();
        actualizarInfo(); 
        update();
    }
    
    private void actualizarInfo() throws Exception{
        listaCita = service.citasDisponibles(before, after, lugarCita); 
    }
    
    private void parametrosInicializacion(ServiceModel service) {
        initComponents();
        this.service = service;
        this.model = new DefaultTableModel();
        model.addColumn("Hora");
        table = new JTable(model);
        jPanel2.add(new JScrollPane(table));
        setSize(500, 200);
        setLocation(10,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Listado de Productos");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        int index = table.getSelectedRow();
        if(!listaCita.isEmpty()){
            new GUISolicitarCita(listaCita.get(index)).setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Sin coincidencias para la busqueda");
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    public void update() {
        this.setVisible(true);
        model.setRowCount(0);
        for (Cita c : listaCita) {
            model.addRow(new Object[]{"" + c.getHora()});
        }
        table.paintImmediately(table.getBounds());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
}
