/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Statuses;
import org.openapitools.client.model.WebhookStatus;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Class7TestingApi
 */
@Ignore
public class Class7TestingApiTest {

    private final Class7TestingApi api = new Class7TestingApi();

    
    /**
     * Returns instance status changes history.
     *
     * Requires enable \&quot;instanceStatuses\&quot; option for collecting data.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void instanceStatusesTest() throws ApiException {
        Integer minTime = null;
        Integer maxTime = null;
        Statuses response = api.instanceStatuses(minTime, maxTime);

        // TODO: test validations
    }
    
    /**
     * Returns webhook status for message.
     *
     * Requires enable \&quot;webhookStatuses\&quot; option for collecting data.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhookStatusesTest() throws ApiException {
        String msgId = null;
        WebhookStatus response = api.webhookStatuses(msgId);

        // TODO: test validations
    }
    
}
