/*
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BanSettings;
import org.openapitools.client.model.BanTestAction;
import org.openapitools.client.model.BanTestStatus;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Class6BanApi
 */
@Ignore
public class Class6BanApiTest {

    private final Class6BanApi api = new Class6BanApi();

    
    /**
     * Test ban settings
     *
     * Send the phone number to find out if the instance is banning it
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void banTestTest() throws ApiException {
        BanTestAction banTestAction = null;
        BanTestStatus response = api.banTest(banTestAction);

        // TODO: test validations
    }
    
    /**
     * Get settings
     *
     * **banPhoneMask** - Regular expression on which bans on numbers will be sent  **preBanMessage** - Warning message If it is set, a message will be sent before sending the ban.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBanSettingsTest() throws ApiException {
        BanSettings response = api.getBanSettings();

        // TODO: test validations
    }
    
    /**
     * Set settings
     *
     * **banPhoneMask** - Regular expression on which bans on numbers will be sent  **preBanMessage** - Warning message If it is set, a message will be sent before sending the ban.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setBanSettingsTest() throws ApiException {
        BanSettings banSettings = null;
        BanSettings response = api.setBanSettings(banSettings);

        // TODO: test validations
    }
    
}
