package blood4life.User.presentacion.Funcionario;

import blood4life.User.domain.commands.CreateCommand;
import blood4life.User.domain.commands.DeleteCommand;
import blood4life.User.domain.commands.FindAllCommand;
import blood4life.User.domain.commands.FindCommand;
import blood4life.User.domain.commands.Invoker;
import blood4life.User.domain.commands.UpdateCommand;
import blood4life.User.domain.services.GestorServicesImpl;
import blood4life.User.domain.services.ServicesEnum;
import blood4life.User.infra.Messages;
import blood4life.commons.domain.Cita;
import java.sql.Date;
import java.sql.Time;
import javax.swing.table.DefaultTableModel;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

public class GUICitas extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    /**
     * Instancia del invocador para poder enviar comandos al receptor
     * FoodService
     */
    private final Invoker invoker;
    GestorServicesImpl serv;
    private Object txtHora;
    private int id_lugar = -1;

    /**
     * Constructor
     */
    public GUICitas(int id_lugar, GestorServicesImpl serv) {
        this.id_lugar = id_lugar;
        invoker = new Invoker();
        this.serv = serv;
        initComponents();
        setSize(870, 300);
        loadDataTable();
        loadDataCombo();
        initStateButtons();
        setLocationRelativeTo(null);
    }

    /**
     * Carga los tipos de comida en el jComboBox
     */
    private void loadDataCombo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
    }

    /**
     * Poner los botones en su estado inicial
     */
    private void initStateButtons() {
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUndo.setEnabled(invoker.hasCommandUndo());
    }

    /**
     * Carga las comidas en el jTable
     */
    private void loadDataTable() {
        try {
            invoker.setCommand(new FindAllCommand(null, serv.getImpl(ServicesEnum.CitaService)));
            invoker.execute();
            FindAllCommand findAllCommand = (FindAllCommand) invoker.getCommand();
            List<Cita> components = (List<Cita>) findAllCommand.getList();
            DefaultTableModel modelTable = (DefaultTableModel) tblData.getModel();
            clearData(modelTable);
            for (Cita component : components) {
                Object[] fila = new Object[3];
                fila[0] = String.valueOf(component.getCodigo());
                fila[1] = component.getCupos();
                fila[2] = component.getFecha();
                fila[3] = component.getHora();
                modelTable.addRow(fila);
            }
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Elimina las filas del jTable
     *
     * @param modelTable modelo de datos del jTable
     */
    private void clearData(DefaultTableModel modelTable) {
        while (modelTable.getRowCount() > 0) {
            modelTable.removeRow(0);
        }
    }

    /**
     * Mensaje inicial del panel superior
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblCupos = new javax.swing.JLabel();
        txtCupos = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        pnlSur = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnlEste = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setTitle("Lugares ");

        pnlCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCentro.setLayout(new java.awt.GridLayout(3, 2));

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("*Id:");
        pnlCentro.add(lblId);

        txtId.setPreferredSize(new java.awt.Dimension(150, 32));
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        pnlCentro.add(txtId);

        lblCupos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCupos.setText("*Cupos:");
        pnlCentro.add(lblCupos);
        pnlCentro.add(txtCupos);

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("*Fecha");
        pnlCentro.add(lblFecha);
        pnlCentro.add(txtFecha);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlSur.add(btnAdd);

        btnUpdate.setText("Modificar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlSur.add(btnUpdate);

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlSur.add(btnDelete);

        btnUndo.setText("Deshacer");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        pnlSur.add(btnUndo);

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlSur.add(btnClose);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pnlEste.setBorder(new javax.swing.border.MatteBorder(null));
        pnlEste.setLayout(new java.awt.BorderLayout());

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cupos", "Fecha", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        pnlEste.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlEste, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    public String getTxtyId() {
        return txtId.getText();
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String idCita = txtId.getText();
            if (idCita.isEmpty()) {
                Messages.warningMessage("Debe agregar un ID a la cita", "Atención");
                txtId.requestFocus();
                return;
            }

            int id = Integer.parseInt(txtId.getText());
            int cupos = Integer.parseInt(txtCupos.getText());
            Date fecha = Date.valueOf(txtFecha.getText());
            Time hora = null; //no pude agregarle la fila para la  hora :'c

            addCita(id, cupos, fecha, hora);

            Messages.successMessage("Cita agregada con éxito", "Atención");
            clearControls();
            initStateButtons();
            loadDataTable();
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * Llama a la logica de negocio para agregar la cita mediante el comando
     *
     * @param id identificador de la cita
     * @param cupos
     * @param fecha fecha de la cita
     * @param hora hora de la cita
     */
    private void addCita(int codigo, int cupos, Date fecha, Time hora) throws Exception {
        Cita cita = new Cita(codigo, cupos, fecha, hora);
        //Fija el comando del invoker
        invoker.setCommand(new CreateCommand(cita, serv.getImpl(ServicesEnum.CitaService)));
        //Ejecuta el comando
        invoker.execute();
    }


    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String idCita = txtId.getText();
        if (idCita.isEmpty()) {
            Messages.warningMessage("Debe agregar un ID para la cita", "Atención");
            txtId.requestFocus();
            return;
        }
        // Preparar los datos
        int id = Integer.parseInt(txtId.getText());
        int cupos = Integer.parseInt(txtCupos.getText());
        Date fecha = Date.valueOf(txtFecha.getText());
        Time hora = null; //Time.valueOf(txtHora.getText());  

        // Crea la cita con los nuevos datos
        Cita cita = new Cita(id, cupos, fecha, hora);

        try {
            // Traer la cita previa
            invoker.setCommand(new FindCommand(String.valueOf(id), serv.getImpl(ServicesEnum.CitaService)));
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        FindCommand findcommand = (FindCommand) invoker.getCommand();
        findcommand.setArgs(id);
        invoker.execute();

        //la cita previa debe crearse en una nueva instancia
        Cita compAux = (Cita) findcommand.getElement();
        Cita previous = new Cita(compAux.getCodigo(), compAux.getCupos(), compAux.getFecha(), compAux.getHora());

        //Modifica la cita y guarda el previo
        updateCita(cita, previous);

        Messages.successMessage("Lugar modificada con éxito", "Atención");
        clearControls();
        initStateButtons();
        try {
            loadDataTable();
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    /**
     * Llama a la logica de negocio para modificar comida mediante el comando
     *
     * @param food lugar a editar
     * @param previous lugar antes de ser modificada
     */
    private void updateCita(Cita cita, Cita previous) {
        try {
            //Fija el UpdateCommand
            invoker.setCommand(new UpdateCommand(cita, serv.getImpl(ServicesEnum.CitaService)));
            UpdateCommand updateCommand = (UpdateCommand) invoker.getCommand();
            //Fija la cita  previa
            updateCommand.setPrevious(previous);
            //Ejecuta el comando
            invoker.execute();
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        String strId = txtId.getText().trim();
        if (strId.isEmpty()) {
            return;
        }

        try {
            //Fija el comando del invoker para buscar cita por id
            invoker.setCommand(new FindCommand(null, serv.getImpl(ServicesEnum.CitaService)));
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Pasa parámetros al comando
        FindCommand findByIdCommand = (FindCommand) invoker.getCommand();
        findByIdCommand.setArgs(strId);
        //Ejecuta el comando
        invoker.execute();
        Cita cita = (Cita) findByIdCommand.getElement();

        if (cita == null) {
            //Agregar
            btnAdd.setEnabled(true);
            btnUndo.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);

        } else {
            //Editar
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUndo.setEnabled(false);
            txtCupos.setText(String.valueOf(cita.getCupos()));
            txtFecha.setText(String.valueOf(cita.getFecha()));
        }
    }//GEN-LAST:event_txtIdFocusLost

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        //Ejecuta el comando deshacer
        invoker.undo();
        try {
            loadDataTable();
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        initStateButtons();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtIdFocusLost(null);
            txtCupos.requestFocus();
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String strId = txtId.getText().trim();

            // Traer la cita previa
            invoker.setCommand(new FindCommand(strId, serv.getImpl(ServicesEnum.CitaService)));
            FindCommand findByIdCommand = (FindCommand) invoker.getCommand();
            invoker.execute();
            Cita compAux = (Cita) findByIdCommand.getElement();
            Cita cita = new Cita(compAux.getCodigo(), compAux.getCupos(), compAux.getFecha(), compAux.getHora());

            //Elimina la cita
            deleteCita(cita);

            Messages.successMessage("Comida eliminada con éxito", "Atención");
            clearControls();
            initStateButtons();
            loadDataTable();
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed
    /**
     * Llama a la logica de negocio para cita mediante el comando
     *
     * @param cita cita a eliminar
     *
     */
    private void deleteCita(Cita cita) {
        try {
            //Fija el comando del invoker
            invoker.setCommand(new DeleteCommand(cita, serv.getImpl(ServicesEnum.CitaService)));
            //Ejecuta el comando
            invoker.execute();
        } catch (Exception ex) {
            Logger.getLogger(GUICitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Limpia las cajas de texto
     */
    public void clearControls() {
        txtId.setText("");
        txtCupos.setText("");
        txtFecha.setText("");
    }

    public static void main(String[] args) {
        GUICitas gui = new GUICitas(1, new GestorServicesImpl());
        gui.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUndo;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCupos;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlEste;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtCupos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
